-- Secure Discord source-owner linking.
--
-- The public session UUID is intentionally not a bearer credential. Completion also
-- requires the same Discord identity in a Privy-signed identity token and a double-submit
-- same-site state value generated by the web application. The bot creates sessions only
-- from a signed interaction whose member has Manage Guild.
--
-- Rollback: supabase/rollback/26-discord-owner-linking.sql.

create table if not exists app_private.discord_owner_link_sessions (
  id uuid primary key default gen_random_uuid(),
  discord_guild_id text not null check (discord_guild_id ~ '^\d{17,20}$'),
  discord_user_id text not null check (discord_user_id ~ '^\d{17,20}$'),
  discord_username text,
  manage_guild_verified boolean not null,
  source_group_id uuid references public.approved_groups(id) on delete restrict,
  status text not null default 'pending'
    check (status in ('pending', 'completed', 'expired', 'cancelled')),
  expires_at timestamptz not null,
  completed_at timestamptz,
  completed_by_privy_user_id text references app_private.app_users(privy_user_id) on delete restrict,
  created_at timestamptz not null default now(),
  check (expires_at > created_at),
  check (status <> 'completed' or (completed_at is not null and completed_by_privy_user_id is not null))
);

create index if not exists discord_owner_link_sessions_pending_idx
  on app_private.discord_owner_link_sessions (discord_guild_id, discord_user_id, expires_at desc)
  where status = 'pending';

create table if not exists app_private.discord_ownership_events (
  id uuid primary key default gen_random_uuid(),
  event_type text not null check (event_type in (
    'link-session.created', 'identity.linked', 'source.claimed',
    'identity.revoked', 'source.revoked', 'source.relinked', 'admin.resolved'
  )),
  source_group_id uuid references public.approved_groups(id) on delete restrict,
  discord_identity_id uuid references app_private.auth_identities(id) on delete restrict,
  link_session_id uuid references app_private.discord_owner_link_sessions(id) on delete restrict,
  previous_owner_privy_user_id text,
  next_owner_privy_user_id text,
  actor_type text not null check (actor_type in ('discord-user', 'account-user', 'admin', 'system')),
  actor_id text not null,
  reason text,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now()
);

create index if not exists discord_ownership_events_source_idx
  on app_private.discord_ownership_events (source_group_id, created_at desc);
create index if not exists discord_ownership_events_identity_idx
  on app_private.discord_ownership_events (discord_identity_id, created_at desc);

alter table app_private.discord_owner_link_sessions enable row level security;
alter table app_private.discord_ownership_events enable row level security;
revoke all on table app_private.discord_owner_link_sessions from public, anon, authenticated;
revoke all on table app_private.discord_ownership_events from public, anon, authenticated;

create or replace function public.bot_create_discord_owner_link(
  p_secret text,
  p_guild_id text,
  p_discord_user_id text,
  p_discord_username text,
  p_manage_guild_verified boolean
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_session app_private.discord_owner_link_sessions%rowtype;
  v_group_id uuid;
begin
  if not app_private.bot_secret_ok(p_secret) then
    raise exception 'unauthorized' using errcode = '42501';
  end if;
  if p_guild_id !~ '^\d{17,20}$' or p_discord_user_id !~ '^\d{17,20}$' then
    raise exception 'invalid Discord identity' using errcode = '22023';
  end if;
  if p_manage_guild_verified is distinct from true then
    raise exception 'Manage Server permission required' using errcode = '42501';
  end if;

  select g.id into v_group_id
  from public.approved_groups g
  where g.discord_guild_id = p_guild_id
    and g.active = true
    and g.verification_status = 'approved'
    and g.removed_at is null
    and g.suspended_at is null
  order by g.created_at asc
  limit 1;

  update app_private.discord_owner_link_sessions
  set status = 'cancelled'
  where discord_guild_id = p_guild_id
    and discord_user_id = p_discord_user_id
    and status = 'pending';

  insert into app_private.discord_owner_link_sessions (
    discord_guild_id, discord_user_id, discord_username,
    manage_guild_verified, source_group_id, expires_at
  ) values (
    p_guild_id, p_discord_user_id, nullif(left(trim(coalesce(p_discord_username, '')), 100), ''),
    true, v_group_id, now() + interval '10 minutes'
  ) returning * into v_session;

  insert into app_private.discord_ownership_events (
    event_type, source_group_id, link_session_id, actor_type, actor_id, metadata
  ) values (
    'link-session.created', v_group_id, v_session.id, 'discord-user', p_discord_user_id,
    jsonb_build_object('guildId', p_guild_id, 'expiresAt', v_session.expires_at)
  );

  return jsonb_build_object(
    'ok', true,
    'sessionId', v_session.id,
    'expiresAt', v_session.expires_at,
    'sourceEligible', v_group_id is not null
  );
end;
$$;

create or replace function public.app_user_get_discord_link_session(
  p_secret text,
  p_privy_user_id text,
  p_session_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_session app_private.discord_owner_link_sessions%rowtype;
  v_source_name text;
begin
  if not app_private.admin_secret_ok(p_secret) then
    raise exception 'unauthorized' using errcode = '42501';
  end if;
  perform app_private.ensure_app_user(p_privy_user_id);

  update app_private.discord_owner_link_sessions
  set status = 'expired'
  where id = p_session_id and status = 'pending' and expires_at <= now();

  select * into v_session
  from app_private.discord_owner_link_sessions s
  where s.id = p_session_id;
  if not found then
    return jsonb_build_object('ok', false, 'status', 404, 'error', 'link session not found');
  end if;
  select g.name into v_source_name
  from public.approved_groups g where g.id = v_session.source_group_id;

  return jsonb_build_object(
    'ok', true,
    'sessionId', v_session.id,
    'status', v_session.status,
    'expiresAt', v_session.expires_at,
    'discordGuildId', v_session.discord_guild_id,
    'discordUserId', v_session.discord_user_id,
    'discordUsername', v_session.discord_username,
    'sourceGroupId', v_session.source_group_id,
    'sourceName', v_source_name,
    'sourceEligible', v_session.source_group_id is not null
  );
end;
$$;

create or replace function public.app_user_complete_discord_owner_link(
  p_secret text,
  p_privy_user_id text,
  p_session_id uuid,
  p_verified_discord_user_id text,
  p_verified_discord_username text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_session app_private.discord_owner_link_sessions%rowtype;
  v_identity app_private.auth_identities%rowtype;
  v_existing_owner text;
  v_current app_private.source_ownership_history%rowtype;
  v_claimed boolean := false;
  v_claim_status text := 'no-eligible-source';
begin
  if not app_private.admin_secret_ok(p_secret) then
    raise exception 'unauthorized' using errcode = '42501';
  end if;
  if p_verified_discord_user_id !~ '^\d{17,20}$' then
    raise exception 'verified Discord identity required' using errcode = '22023';
  end if;
  perform app_private.ensure_app_user(p_privy_user_id);

  select * into v_session
  from app_private.discord_owner_link_sessions
  where id = p_session_id
  for update;
  if not found then
    return jsonb_build_object('ok', false, 'status', 404, 'error', 'link session not found');
  end if;
  if v_session.status <> 'pending' then
    return jsonb_build_object('ok', false, 'status', 409, 'error', 'link session already used');
  end if;
  if v_session.expires_at <= now() then
    update app_private.discord_owner_link_sessions set status = 'expired' where id = v_session.id;
    return jsonb_build_object('ok', false, 'status', 410, 'error', 'link session expired');
  end if;
  if not v_session.manage_guild_verified or v_session.discord_user_id <> p_verified_discord_user_id then
    raise exception 'Discord identity does not match link creator' using errcode = '42501';
  end if;

  select i.privy_user_id into v_existing_owner
  from app_private.auth_identities i
  where i.provider = 'discord_oauth'
    and i.provider_subject = p_verified_discord_user_id
    and i.revoked_at is null;
  if v_existing_owner is not null and v_existing_owner <> p_privy_user_id then
    return jsonb_build_object('ok', false, 'status', 409, 'error', 'Discord identity already linked to another account');
  end if;

  insert into app_private.auth_identities (
    privy_user_id, provider, provider_subject, email_verified,
    last_verified_at, revoked_at
  ) values (
    p_privy_user_id, 'discord_oauth', p_verified_discord_user_id, false, now(), null
  )
  on conflict (provider, provider_subject) do update
  set privy_user_id = excluded.privy_user_id,
      last_verified_at = now(),
      revoked_at = null
  where app_private.auth_identities.revoked_at is not null
     or app_private.auth_identities.privy_user_id = excluded.privy_user_id
  returning * into v_identity;
  if v_identity.id is null then
    return jsonb_build_object('ok', false, 'status', 409, 'error', 'Discord identity could not be linked');
  end if;

  insert into app_private.discord_ownership_events (
    event_type, source_group_id, discord_identity_id, link_session_id,
    next_owner_privy_user_id, actor_type, actor_id, metadata
  ) values (
    'identity.linked', v_session.source_group_id, v_identity.id, v_session.id,
    p_privy_user_id, 'account-user', p_privy_user_id,
    jsonb_build_object('discordUserId', p_verified_discord_user_id, 'discordUsername', left(coalesce(p_verified_discord_username, ''), 100))
  );

  if v_session.source_group_id is not null then
    select g.owner_privy_user_id into v_existing_owner
    from public.approved_groups g
    where g.id = v_session.source_group_id
      and g.discord_guild_id = v_session.discord_guild_id
      and g.active = true
      and g.verification_status = 'approved'
      and g.removed_at is null
      and g.suspended_at is null
    for update;
    if not found then
      v_claim_status := 'source-no-longer-eligible';
    elsif v_existing_owner is not null and v_existing_owner <> p_privy_user_id then
      v_claim_status := 'admin-resolution-required';
    else
      select * into v_current
      from app_private.source_ownership_history h
      where h.source_group_id = v_session.source_group_id and h.valid_to is null
      for update;
      if found and v_current.owner_privy_user_id <> p_privy_user_id then
        v_claim_status := 'admin-resolution-required';
      else
        if not found then
          insert into app_private.source_ownership_history (
            source_group_id, owner_privy_user_id, verified_identity_id,
            creator_fee_bps, reason
          ) select
            g.id, p_privy_user_id, v_identity.id, g.creator_fee_bps,
            'Verified Discord Manage Server link'
          from public.approved_groups g where g.id = v_session.source_group_id;
        end if;
        update public.approved_groups
        set owner_privy_user_id = p_privy_user_id
        where id = v_session.source_group_id;
        v_claimed := true;
        v_claim_status := 'claimed';

        insert into app_private.discord_ownership_events (
          event_type, source_group_id, discord_identity_id, link_session_id,
          previous_owner_privy_user_id, next_owner_privy_user_id,
          actor_type, actor_id, reason
        ) values (
          'source.claimed', v_session.source_group_id, v_identity.id, v_session.id,
          v_existing_owner, p_privy_user_id, 'account-user', p_privy_user_id,
          'Verified Discord Manage Server link'
        );
      end if;
    end if;
  end if;

  update app_private.discord_owner_link_sessions
  set status = 'completed', completed_at = now(), completed_by_privy_user_id = p_privy_user_id
  where id = v_session.id;

  return jsonb_build_object(
    'ok', true,
    'discordUserId', p_verified_discord_user_id,
    'discordUsername', nullif(left(trim(coalesce(p_verified_discord_username, '')), 100), ''),
    'sourceGroupId', v_session.source_group_id,
    'sourceClaimed', v_claimed,
    'claimStatus', v_claim_status
  );
end;
$$;

create or replace function public.app_user_discord_ownership_summary(
  p_secret text,
  p_privy_user_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_identity jsonb;
  v_sources jsonb;
  v_payouts jsonb;
begin
  if not app_private.admin_secret_ok(p_secret) then
    raise exception 'unauthorized' using errcode = '42501';
  end if;
  perform app_private.ensure_app_user(p_privy_user_id);

  select jsonb_build_object(
    'id', i.id,
    'discordUserId', i.provider_subject,
    'discordUsername', (
      select nullif(e.metadata->>'discordUsername', '')
      from app_private.discord_ownership_events e
      where e.discord_identity_id = i.id and e.event_type = 'identity.linked'
      order by e.created_at desc limit 1
    ),
    'linkedAt', i.linked_at,
    'lastVerifiedAt', i.last_verified_at
  ) into v_identity
  from app_private.auth_identities i
  where i.privy_user_id = p_privy_user_id
    and i.provider = 'discord_oauth'
    and i.revoked_at is null
  order by i.last_verified_at desc
  limit 1;

  select coalesce(jsonb_agg(to_jsonb(x) order by x."sourceName"), '[]'::jsonb)
  into v_sources
  from (
    select
      g.id as "sourceGroupId",
      g.name as "sourceName",
      g.public_slug as "publicSlug",
      g.verification_status as "verificationStatus",
      h.valid_from as "ownedSince",
      h.creator_fee_bps as "commissionRateBps",
      (select count(*)::integer from public.calls c
        where c.group_id = g.id and c.parse_status = 'accepted') as "eligibleCalls",
      coalesce((select sum(e.gross_notional_lamports)
        from app_private.trade_executions e
        where e.status = 'reconciled' and e.source_group_id_snapshot = g.id), 0)::bigint as "confirmedEligibleVolumeLamports",
      coalesce((
        select sum(l.amount_lamports)
        from app_private.commission_ledger_entries l
        where l.account_owner_privy_user_id = p_privy_user_id
          and l.account_type = 'creator'
          and l.source_type = 'discord'
          and l.source_id = g.id::text
          and l.available_at <= now()
      ), 0)::bigint as "confirmedEarningsLamports",
      coalesce((
        select sum(l.amount_lamports)
        from app_private.commission_ledger_entries l
        where l.account_owner_privy_user_id = p_privy_user_id
          and l.account_type = 'creator'
          and l.source_type = 'discord'
          and l.source_id = g.id::text
          and l.available_at > now()
      ), 0)::bigint as "pendingEarningsLamports"
    from app_private.source_ownership_history h
    join public.approved_groups g on g.id = h.source_group_id
    where h.owner_privy_user_id = p_privy_user_id and h.valid_to is null
  ) x;

  select coalesce(jsonb_agg(to_jsonb(x) order by x."requestedAt" desc), '[]'::jsonb)
  into v_payouts
  from (
    select p.id, p.gross_lamports as "grossLamports", p.net_lamports as "netLamports",
      p.status, p.requested_at as "requestedAt", p.processed_at as "processedAt",
      p.tx_signature as "txSignature"
    from app_private.payout_requests p
    where p.owner_privy_user_id = p_privy_user_id
    order by p.requested_at desc
    limit 25
  ) x;

  return jsonb_build_object(
    'connectedDiscord', v_identity,
    'sources', v_sources,
    'payouts', v_payouts
  );
end;
$$;

create or replace function public.app_user_revoke_discord_owner_link(
  p_secret text,
  p_privy_user_id text,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_identity app_private.auth_identities%rowtype;
  v_row record;
begin
  if not app_private.admin_secret_ok(p_secret) then
    raise exception 'unauthorized' using errcode = '42501';
  end if;
  if nullif(trim(coalesce(p_reason, '')), '') is null then
    raise exception 'reason required' using errcode = '22023';
  end if;
  select * into v_identity
  from app_private.auth_identities i
  where i.privy_user_id = p_privy_user_id and i.provider = 'discord_oauth' and i.revoked_at is null
  order by i.last_verified_at desc limit 1 for update;
  if not found then
    return jsonb_build_object('ok', true, 'revoked', false);
  end if;

  for v_row in
    select h.id, h.source_group_id
    from app_private.source_ownership_history h
    where h.owner_privy_user_id = p_privy_user_id
      and h.verified_identity_id = v_identity.id
      and h.valid_to is null
    for update
  loop
    update app_private.source_ownership_history
    set valid_to = now(), reason = left(trim(p_reason), 500)
    where id = v_row.id;
    update public.approved_groups
    set owner_privy_user_id = null
    where id = v_row.source_group_id and owner_privy_user_id = p_privy_user_id;
    insert into app_private.discord_ownership_events (
      event_type, source_group_id, discord_identity_id,
      previous_owner_privy_user_id, actor_type, actor_id, reason
    ) values (
      'source.revoked', v_row.source_group_id, v_identity.id,
      p_privy_user_id, 'account-user', p_privy_user_id, left(trim(p_reason), 500)
    );
  end loop;

  update app_private.auth_identities set revoked_at = now() where id = v_identity.id;
  insert into app_private.discord_ownership_events (
    event_type, discord_identity_id, previous_owner_privy_user_id,
    actor_type, actor_id, reason
  ) values (
    'identity.revoked', v_identity.id, p_privy_user_id,
    'account-user', p_privy_user_id, left(trim(p_reason), 500)
  );
  return jsonb_build_object('ok', true, 'revoked', true);
end;
$$;

create or replace function public.admin_list_discord_ownership(
  p_secret text,
  p_actor_privy_user_id text,
  p_limit integer default 200
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_sources jsonb;
  v_sessions jsonb;
  v_events jsonb;
begin
  if not app_private.admin_secret_ok(p_secret) then
    raise exception 'unauthorized' using errcode = '42501';
  end if;
  perform app_private.require_app_admin(p_actor_privy_user_id);

  select coalesce(jsonb_agg(to_jsonb(x) order by x."sourceName"), '[]'::jsonb) into v_sources
  from (
    select g.id as "sourceGroupId", g.name as "sourceName", g.discord_guild_id as "discordGuildId",
      g.owner_privy_user_id as "ownerPrivyUserId", g.creator_fee_bps as "commissionRateBps",
      h.id as "ownershipHistoryId", h.verified_identity_id as "discordIdentityId",
      i.provider_subject as "discordUserId", h.valid_from as "validFrom",
      g.verification_status as "verificationStatus"
    from public.approved_groups g
    left join app_private.source_ownership_history h on h.source_group_id = g.id and h.valid_to is null
    left join app_private.auth_identities i on i.id = h.verified_identity_id and i.revoked_at is null
    where g.discord_guild_id is not null
    limit greatest(1, least(coalesce(p_limit, 200), 500))
  ) x;

  select coalesce(jsonb_agg(to_jsonb(x) order by x."createdAt" desc), '[]'::jsonb) into v_sessions
  from (
    select s.id, s.discord_guild_id as "discordGuildId", s.discord_user_id as "discordUserId",
      s.discord_username as "discordUsername", s.source_group_id as "sourceGroupId",
      s.status, s.expires_at as "expiresAt", s.completed_at as "completedAt",
      s.completed_by_privy_user_id as "completedByPrivyUserId", s.created_at as "createdAt"
    from app_private.discord_owner_link_sessions s
    order by s.created_at desc
    limit greatest(1, least(coalesce(p_limit, 200), 500))
  ) x;

  select coalesce(jsonb_agg(to_jsonb(x) order by x."createdAt" desc), '[]'::jsonb) into v_events
  from (
    select e.id, e.event_type as "eventType", e.source_group_id as "sourceGroupId",
      e.discord_identity_id as "discordIdentityId", e.previous_owner_privy_user_id as "previousOwnerPrivyUserId",
      e.next_owner_privy_user_id as "nextOwnerPrivyUserId", e.actor_type as "actorType",
      e.actor_id as "actorId", e.reason, e.created_at as "createdAt"
    from app_private.discord_ownership_events e
    order by e.created_at desc
    limit greatest(1, least(coalesce(p_limit, 200), 500))
  ) x;
  return jsonb_build_object('ok', true, 'sources', v_sources, 'sessions', v_sessions, 'events', v_events);
end;
$$;

create or replace function public.admin_resolve_discord_ownership(
  p_secret text,
  p_actor_privy_user_id text,
  p_source_group_id uuid,
  p_action text,
  p_target_privy_user_id text,
  p_discord_user_id text,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_group public.approved_groups%rowtype;
  v_current app_private.source_ownership_history%rowtype;
  v_identity app_private.auth_identities%rowtype;
  v_previous text;
begin
  if not app_private.admin_secret_ok(p_secret) then
    raise exception 'unauthorized' using errcode = '42501';
  end if;
  perform app_private.require_app_admin(p_actor_privy_user_id);
  if lower(p_action) not in ('assign', 'revoke') then
    raise exception 'invalid ownership action' using errcode = '22023';
  end if;
  if nullif(trim(coalesce(p_reason, '')), '') is null then
    raise exception 'reason required' using errcode = '22023';
  end if;

  select * into v_group from public.approved_groups where id = p_source_group_id for update;
  if not found then raise exception 'source not found' using errcode = 'P0002'; end if;
  v_previous := v_group.owner_privy_user_id;
  select * into v_current from app_private.source_ownership_history
  where source_group_id = p_source_group_id and valid_to is null for update;

  if lower(p_action) = 'assign' then
    if nullif(trim(coalesce(p_target_privy_user_id, '')), '') is null or p_discord_user_id !~ '^\d{17,20}$' then
      raise exception 'verified target identity required' using errcode = '22023';
    end if;
    select * into v_identity from app_private.auth_identities i
    where i.provider = 'discord_oauth' and i.provider_subject = p_discord_user_id
      and i.privy_user_id = p_target_privy_user_id and i.revoked_at is null
    for update;
    if not found then raise exception 'active verified Discord identity not found' using errcode = 'P0002'; end if;
    if v_current.id is not null then
      update app_private.source_ownership_history
      set valid_to = now(), reason = left(trim(p_reason), 500)
      where id = v_current.id;
    end if;
    insert into app_private.source_ownership_history (
      source_group_id, owner_privy_user_id, verified_identity_id, creator_fee_bps, reason
    ) values (
      p_source_group_id, p_target_privy_user_id, v_identity.id, v_group.creator_fee_bps,
      'Admin dispute resolution: ' || left(trim(p_reason), 450)
    );
    update public.approved_groups set owner_privy_user_id = p_target_privy_user_id where id = p_source_group_id;
    insert into app_private.discord_ownership_events (
      event_type, source_group_id, discord_identity_id, previous_owner_privy_user_id,
      next_owner_privy_user_id, actor_type, actor_id, reason
    ) values (
      case when v_previous is null then 'admin.resolved' else 'source.relinked' end,
      p_source_group_id, v_identity.id, v_previous, p_target_privy_user_id,
      'admin', p_actor_privy_user_id, left(trim(p_reason), 500)
    );
  else
    if v_current.id is not null then
      update app_private.source_ownership_history
      set valid_to = now(), reason = left(trim(p_reason), 500)
      where id = v_current.id;
    end if;
    update public.approved_groups set owner_privy_user_id = null where id = p_source_group_id;
    insert into app_private.discord_ownership_events (
      event_type, source_group_id, discord_identity_id, previous_owner_privy_user_id,
      actor_type, actor_id, reason
    ) values (
      'admin.resolved', p_source_group_id, v_current.verified_identity_id, v_previous,
      'admin', p_actor_privy_user_id, left(trim(p_reason), 500)
    );
  end if;

  insert into app_private.admin_audit_log (
    actor_privy_user_id, action, target_type, target_id, reason, previous_state, next_state
  ) values (
    p_actor_privy_user_id, 'discord-ownership.' || lower(p_action), 'discord-source',
    p_source_group_id::text, left(trim(p_reason), 500),
    jsonb_build_object('ownerPrivyUserId', v_previous),
    jsonb_build_object('ownerPrivyUserId', case when lower(p_action) = 'assign' then p_target_privy_user_id else null end)
  );
  return jsonb_build_object('ok', true, 'sourceGroupId', p_source_group_id, 'action', lower(p_action));
end;
$$;

-- Creator commission for a Discord source is valid only while the source has a current,
-- verified ownership row tied to a non-revoked Discord identity. The trigger runs before
-- the existing fee validator and removes only the creator allocation; retained platform
-- revenue absorbs that share, so the 200 bps platform fee remains balanced.
create or replace function app_private.enforce_verified_discord_creator()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.source_group_id_snapshot is not null and not exists (
    select 1
    from app_private.source_ownership_history h
    join app_private.auth_identities i on i.id = h.verified_identity_id
    where h.source_group_id = new.source_group_id_snapshot
      and h.valid_to is null
      and h.owner_privy_user_id = new.creator_privy_user_id_snapshot
      and i.provider = 'discord_oauth'
      and i.privy_user_id = h.owner_privy_user_id
      and i.revoked_at is null
  ) then
    new.creator_privy_user_id_snapshot := null;
    new.creator_fee_bps_snapshot := 0;
    new.creator_fee_lamports := 0;
  end if;
  return new;
end;
$$;

drop trigger if exists trade_executions_00_verified_discord_creator on app_private.trade_executions;
create trigger trade_executions_00_verified_discord_creator
before insert on app_private.trade_executions
for each row execute function app_private.enforce_verified_discord_creator();

revoke execute on function public.bot_create_discord_owner_link(text, text, text, text, boolean) from public, anon, authenticated;
grant execute on function public.bot_create_discord_owner_link(text, text, text, text, boolean) to service_role;
revoke execute on function public.app_user_get_discord_link_session(text, text, uuid) from public, anon, authenticated;
grant execute on function public.app_user_get_discord_link_session(text, text, uuid) to service_role;
revoke execute on function public.app_user_complete_discord_owner_link(text, text, uuid, text, text) from public, anon, authenticated;
grant execute on function public.app_user_complete_discord_owner_link(text, text, uuid, text, text) to service_role;
revoke execute on function public.app_user_discord_ownership_summary(text, text) from public, anon, authenticated;
grant execute on function public.app_user_discord_ownership_summary(text, text) to service_role;
revoke execute on function public.app_user_revoke_discord_owner_link(text, text, text) from public, anon, authenticated;
grant execute on function public.app_user_revoke_discord_owner_link(text, text, text) to service_role;
revoke execute on function public.admin_list_discord_ownership(text, text, integer) from public, anon, authenticated;
grant execute on function public.admin_list_discord_ownership(text, text, integer) to service_role;
revoke execute on function public.admin_resolve_discord_ownership(text, text, uuid, text, text, text, text) from public, anon, authenticated;
grant execute on function public.admin_resolve_discord_ownership(text, text, uuid, text, text, text, text) to service_role;
revoke execute on function app_private.enforce_verified_discord_creator() from public, anon, authenticated;
