#!/usr/bin/env node
// Regenerate the machine-checkable parts of docs/coordination/AI_HANDOFF.md.
//
// Run: npm run handoff        (add --check to fail instead of writing)
//
// WHY THIS EXISTS
// The handoff, the readiness section, and the release evidence file have each gone stale in
// this project, and a stale coordination doc is worse than none — it reads as verification.
// Every fact in the state table below is derivable from the repository, so it is derived
// rather than retyped. Prose sections are hand-written and never touched.

import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";

const HANDOFF = "docs/coordination/AI_HANDOFF.md";
const START = "<!-- handoff:state:start -->";
const END = "<!-- handoff:state:end -->";
const checkOnly = process.argv.includes("--check");

const sh = (cmd) => {
  try { return execSync(cmd, { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim(); }
  catch { return ""; }
};

const branch = sh("git rev-parse --abbrev-ref HEAD") || "?";

// The newest commit NOT authored by this collaboration is Codex's baseline. Commits made
// here carry the Co-Authored-By trailer.
//
// NOTE: do not try to derive this by splitting `--format=%H%x09%b` — %b is multi-line, so
// trailer lines arrive without a hash attached and the parse silently yields nothing,
// which reported "0 commits since" while 45 had landed. Ask git to do the matching.
const claudeCommits = new Set(
  sh('git log --format=%H --grep="Co-Authored-By: Claude" -i master..HEAD')
    .split("\n").filter(Boolean)
);
const allCommits = sh("git log --format=%H master..HEAD").split("\n").filter(Boolean);
const baseline = allCommits.find((h) => !claudeCommits.has(h)) || sh("git rev-parse master");
const shortBaseline = baseline ? baseline.slice(0, 7) : "?";
// If no non-Claude commit exists on the branch, this is the branch base, not a Codex commit.
const baselineLabel = allCommits.some((h) => !claudeCommits.has(h)) ? "Last non-Claude commit" : "Branch base";
const ahead = baseline ? Number(sh(`git rev-list --count ${baseline}..HEAD`) || 0) : allCommits.length;

// Test count comes from running the suite, not from memory.
const testOut = sh("node server/test/run.js");
const testMatch = testOut.match(/(\d+)\s+passed,\s+(\d+)\s+failed/);
const passed = testMatch ? testMatch[1] : "?";
const failed = testMatch ? testMatch[2] : "?";

// Applied migrations are those recorded in the database audit, which is written only after
// a migration actually runs.
let migrations = "unknown";
try {
  const audit = readFileSync("docs/launch/DATABASE_AUDIT.md", "utf8");
  const m = audit.match(/(\w+)\s+migrations?\s+applied/i) || audit.match(/applied\s+(\w+)\s+migrations?/i);
  migrations = m ? m[1] : "see DATABASE_AUDIT.md";
} catch { migrations = "none recorded"; }

// Requirement status is counted from the tracker, which demands evidence per row.
let status = "unknown";
try {
  const impl = readFileSync("docs/coordination/IMPLEMENTATION_STATUS.md", "utf8");
  const count = (re) => (impl.match(re) || []).length;
  status = `${count(/\|\s*PASS\s*\|/g)} PASS · ${count(/\|\s*PARTIAL\s*\|/g)} PARTIAL · ${count(/\|\s*BLOCKED\s*\|/g)} BLOCKED`;
} catch { /* leave unknown */ }

const uncommitted = sh("git status --porcelain").split("\n").filter(Boolean).length;
const pushed = sh(`git rev-list --count origin/${branch}..HEAD 2>/dev/null`) || "?";

const block = `${START}
| | |
|---|---|
| **Branch** | \`${branch}\` |
| **${baselineLabel}** | \`${shortBaseline}\` — **${ahead}** commits landed since |
| **Suite** | \`npm run check\`: **${passed} tests passed, ${failed} failed** |
| **Migrations applied** | ${migrations} |
| **Requirements** | ${status} |
| **Unpushed commits** | ${pushed} |
| **Uncommitted files** | ${uncommitted} |

_Generated by \`npm run handoff\` — do not edit this table by hand._
${END}`;

let doc;
try { doc = readFileSync(HANDOFF, "utf8"); }
catch { console.error(`${HANDOFF} not found`); process.exit(1); }

const hasMarkers = doc.includes(START) && doc.includes(END);
const next = hasMarkers
  ? doc.slice(0, doc.indexOf(START)) + block + doc.slice(doc.indexOf(END) + END.length)
  : null;

if (!hasMarkers) {
  console.error(`${HANDOFF} is missing the ${START} / ${END} markers; add them around the state table.`);
  process.exit(1);
}

if (checkOnly) {
  if (next === doc) { console.log("handoff: state table is current"); process.exit(0); }
  console.error("handoff: state table is STALE — run `npm run handoff`");
  process.exit(1);
}

writeFileSync(HANDOFF, next);
console.log("handoff: state table regenerated");
console.log(block.split("\n").filter((l) => l.startsWith("|")).join("\n"));
